/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jserial;

//import static jserial;

import gnu.io.SerialPortEvent;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import static jdk.nashorn.tools.ShellFunctions.input;


/**
 *
 * @author marlon
 */
public class Tela extends javax.swing.JFrame {

    SerialRxTx serial = new SerialRxTx();
    Protocolo s = serial.getProtocolo();
    boolean conectado = false;
    //Protocolo prt = new Protocolo();

    public Tela() {
        initComponents();
        //SerialRxTx serial = new SerialRxTx();
        btnEnviar1.setEnabled(conectado);
        btnEnviar0.setEnabled(conectado);
        lblLeitura.setText(serial.inputLine);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        cboPortas = new javax.swing.JComboBox<>();
        cboBaud = new javax.swing.JComboBox<>();
        btnConectar = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        btnEnviar0 = new javax.swing.JButton();
        btnEnviar1 = new javax.swing.JButton();
        lblLeitura = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        lblLeitura2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnConectar, org.jdesktop.beansbinding.ELProperty.create("${text}"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        cboPortas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPortasActionPerformed(evt);
            }
        });

        cboBaud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9600", "19200", "38400", "57600", "115200" }));

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        lblStatus.setText("status");

        btnEnviar0.setText("Enviar 0");
        btnEnviar0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviar0ActionPerformed(evt);
            }
        });

        btnEnviar1.setText("Enviar 1");
        btnEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviar1ActionPerformed(evt);
            }
        });

        lblLeitura.setText("lblLeitura");

        jButton1.setText("Ler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lblLeitura2.setText("lblLeitura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAtualizar)
                        .addGap(49, 49, 49)
                        .addComponent(btnConectar))
                    .addComponent(btnEnviar0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnEnviar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboPortas, 0, 206, Short.MAX_VALUE)
                            .addComponent(cboBaud, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLeitura2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLeitura)
                                .addGap(56, 56, 56)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboPortas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboBaud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConectar)
                    .addComponent(btnAtualizar))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar1)
                    .addComponent(btnEnviar0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLeitura)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLeitura2)
                .addGap(3, 3, 3)
                .addComponent(lblStatus)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboPortasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPortasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPortasActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed

        if (conectado) {
            serial.close();
            btnConectar.setText("Conectar");
            lblStatus.setText("Desconectado de " + serial.gettPortName());
            conectado = false;
            btnEnviar1.setEnabled(conectado);
            btnEnviar0.setEnabled(conectado);
            cboPortas.enable(true);
            cboBaud.enable(true);
        } else {
            serial.setPortName(cboPortas.getSelectedItem().toString());
            serial.setBaud(Integer.parseInt(cboBaud.getSelectedItem().toString()));
            btnConectar.setText("Desconectar");
            lblStatus.setText("Conectado em " + serial.gettPortName());
            conectado = true;
            btnEnviar1.setEnabled(conectado);
            btnEnviar0.setEnabled(conectado);
            cboPortas.enable(false);
            cboBaud.enable(false);
            if (serial.iniciaSerial()) {

            } else {
                System.out.println("Erro:" + serial.iniciaSerial());

            }
        }

    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviar1ActionPerformed
        serial.sendData("1");
    }//GEN-LAST:event_btnEnviar1ActionPerformed

    private void btnEnviar0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviar0ActionPerformed
        serial.sendData("0");
    }//GEN-LAST:event_btnEnviar0ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int num1,num2;
        num1 = Integer.parseInt(s.getValor1());
        num2 = Integer.parseInt(s.getValor2());
        if(num1>num2){
            System.out.println("num1 eh maior qe num2");
        }else if(num1==num2){
            System.out.println("num1 eh igual a num2");
        }else{
            System.out.println("num1 eh menor que num2");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        String aux[] = SerialRxTx.listPortsX().split(",");
        cboPortas.removeAllItems();
        for (int x = 0; x < aux.length; x++) {
            cboPortas.addItem(aux[x].replaceAll(" ", ""));
            //cboPortas.
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }
    
    public void leituraSerial(String recebido) {
        lblLeitura.setText(recebido);
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAtualizar;
    public javax.swing.JButton btnConectar;
    private javax.swing.JButton btnEnviar0;
    private javax.swing.JButton btnEnviar1;
    private javax.swing.JComboBox<String> cboBaud;
    public static javax.swing.JComboBox<String> cboPortas;
    private javax.swing.JButton jButton1;
    public static javax.swing.JLabel lblLeitura;
    public static javax.swing.JLabel lblLeitura2;
    private javax.swing.JLabel lblStatus;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
